### PR TITLE
created home page and about me page

### PR DESCRIPTION
**Pull request by MarkNovicio**

### CODE REVIEW

**Comment by zac-heisey** [comment]
Hey Mark,

This assignment doesn't have a PR step. I'm closing this pull request.

Zac

**Comment by MarkNovicio** [comment]
Hey Zac,

Ah ok, but did I miss a step?

Thanks,
Mark

**Comment by zac-heisey** [comment]
Nope, I see that you shared the link to Exercise 2 in the class Slack
channel - that's all you needed to do to "turn in" the project. Thanks!

**Comment by MarkNovicio** [comment]
Ok!! Great! Thanks!

**Pull request closed without merging**
